apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lars-sandbox
resources:
  - namespace.yaml
  - application.yaml
  - channel.yaml
  - placementrule.yaml
  - subscription.yaml
